contact_links:
  - name: Link to Open3D Documentation and Tutorials
    url: http://www.open3d.org/docs/latest/
    about: "Read the documentation and tutorials for Open3D."
  - name: Link to Open3D Discord Server
    url: https://discord.gg/D35BGvn
    about: "Get in touch with the Open3D community on Discord."
